

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrea
 */
public class bienvenido extends javax.swing.JFrame {
    private  Registro  s;

    public Registro getS() {
        return s;
    }

    public void setS(Registro s) {
        this.s = s;
    }

    /**
     * Creates new form Bienvenido
     */
    public bienvenido() {
        initComponents();
        
        s  = new  Registro();
    }
    
    public static String texto = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Gitane = new javax.swing.JButton();
        Snackers = new javax.swing.JButton();
        RED = new javax.swing.JButton();
        Mon = new javax.swing.JButton();
        Green = new javax.swing.JButton();
        Bagel = new javax.swing.JButton();
        Golden = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Yogurt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Bienvenido");

        Gitane.setBackground(new java.awt.Color(255, 153, 204));
        Gitane.setText("Gitane");
        Gitane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GitaneActionPerformed(evt);
            }
        });

        Snackers.setBackground(new java.awt.Color(153, 153, 255));
        Snackers.setText("Snackers");
        Snackers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnackersActionPerformed(evt);
            }
        });

        RED.setBackground(new java.awt.Color(255, 204, 153));
        RED.setText("RED");
        RED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REDActionPerformed(evt);
            }
        });

        Mon.setBackground(new java.awt.Color(255, 255, 153));
        Mon.setText("Monchiz");
        Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonActionPerformed(evt);
            }
        });

        Green.setBackground(new java.awt.Color(204, 255, 204));
        Green.setText("Go Green");
        Green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenActionPerformed(evt);
            }
        });

        Bagel.setBackground(new java.awt.Color(255, 153, 102));
        Bagel.setText("Bagel Bros");
        Bagel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagelActionPerformed(evt);
            }
        });

        Golden.setBackground(new java.awt.Color(153, 204, 255));
        Golden.setText("Golden  Harvest");
        Golden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoldenActionPerformed(evt);
            }
        });

        jButton1.setText("cerrar sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Yogurt.setBackground(new java.awt.Color(255, 153, 153));
        Yogurt.setText("My Yogurt");
        Yogurt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YogurtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Gitane, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Snackers, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RED, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Mon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Green, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bagel)
                                .addGap(18, 18, 18)
                                .addComponent(Golden)
                                .addGap(18, 18, 18)
                                .addComponent(Yogurt))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gitane, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Snackers, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RED, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Green, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bagel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Golden, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Yogurt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SnackersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnackersActionPerformed
        // TODO add your handling code here:
        texto = Snackers.getText();
        Opciones nuevo = new Opciones();
         
      nuevo.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_SnackersActionPerformed

    private void MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonActionPerformed
        // TODO add your handling code here:
        texto = Mon.getText(); 
        Opciones nuevo = new Opciones();
        nuevo.setVisible(true); 
        this.dispose();
        
    }//GEN-LAST:event_MonActionPerformed

    private void GitaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GitaneActionPerformed

texto = Gitane.getText();
        Opciones nuevo = new Opciones();
        nuevo.setVisible(true); 
        this.dispose();
       
        // TODO add your handling code here:
        
        

    }//GEN-LAST:event_GitaneActionPerformed

    private void REDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REDActionPerformed
        // TODO add your handling code here:'
        texto = RED.getText();
         Opciones nuevo = new Opciones();
        nuevo.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_REDActionPerformed

    private void GreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenActionPerformed
        texto = Green.getText();
        Opciones nuevo = new Opciones();
        nuevo.setVisible(true); 
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_GreenActionPerformed

    private void BagelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagelActionPerformed
 texto = Bagel.getText();
        Opciones nuevo = new Opciones();
        nuevo.setVisible(true); 
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BagelActionPerformed

    private void GoldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoldenActionPerformed
        // TODO add your handling code here:
        texto = Golden.getText(); 
        Opciones nuevo = new Opciones();
        nuevo.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_GoldenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //iniciar_sesion nuevo = new iniciar_sesion();
       //nuevo.setVisible(true);
        iniciar_sesion nuevo = new iniciar_sesion();
        nuevo.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void YogurtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YogurtActionPerformed
        // TODO add your handling code here:
        texto = Yogurt.getText(); 
        Opciones nuevo = new Opciones();
        nuevo.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_YogurtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Bagel;
    public static javax.swing.JButton Gitane;
    public static javax.swing.JButton Golden;
    public static javax.swing.JButton Green;
    public static javax.swing.JButton Mon;
    public static javax.swing.JButton RED;
    public static javax.swing.JButton Snackers;
    private javax.swing.JButton Yogurt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
